// Configuration file for HR Jewellers & Sons product filters.
// Includes 17 categories as requested with exact option lists and count tags.

export const FILTER_GROUPS = [
  {
    id: 'price',
    label: 'Price',
    options: [
      { name: 'Below Rs. 10,000', count: 218 },
      { name: 'Rs. 10,000 - Rs. 20,000', count: 658 },
      { name: 'Rs. 20,000 - Rs. 30,000', count: 721 },
      { name: 'Rs. 30,000 - Rs. 40,000', count: 681 },
      { name: 'Rs. 40,000 - Rs. 50,000', count: 775 },
      { name: 'Rs. 50,000 and Above', count: 7361 }
    ]
  },
  {
    id: 'type',
    label: 'Type',
    options: [
      { name: 'Earrings', count: 3160 },
      { name: 'Rings', count: 2650 },
      { name: 'Pendants', count: 1168 },
      { name: 'Necklaces', count: 880 },
      { name: 'Bangles', count: 633 },
      { name: 'Bracelets', count: 482 },
      { name: 'Mangalsutra', count: 274 },
      { name: 'Chains', count: 156 },
      { name: 'Nose Pins', count: 125 },
      { name: 'Watch Accessory', count: 97 },
      { name: 'Adjustable Bracelets', count: 85 },
      { name: 'Charms', count: 62 },
      { name: 'Nose Screws', count: 62 },
      { name: 'Kids Bangles', count: 43 },
      { name: 'Kids Rings', count: 41 },
      { name: 'Kids Bracelets', count: 31 },
      { name: 'Nose Rings', count: 27 },
      { name: 'Anklets', count: 23 },
      { name: 'Adjustable Rings', count: 22 },
      { name: 'Mangalsutra Chains', count: 17 },
      { name: 'Thumb Rings', count: 17 },
      { name: 'Cufflinks', count: 12 },
      { name: 'Brooch', count: 10 },
      { name: 'Midi Rings', count: 9 },
      { name: 'Hair Pins', count: 4 },
      { name: 'Tie Pin', count: 4 },
      { name: 'Maang Tikka', count: 2 }
    ]
  },
  {
    id: 'metal',
    label: 'Metal',
    options: [
      { name: 'Gold', count: 8002 },
      { name: 'Plain Gold/Platinum', count: 2453 },
      { name: 'Rose Gold', count: 1677 },
      { name: 'White Gold', count: 573 },
      { name: 'Platinum', count: 162 }
    ]
  },
  {
    id: 'gender',
    label: 'Gender',
    options: [
      { name: 'Women', count: 8780 },
      { name: 'Men', count: 1004 },
      { name: 'Kids', count: 530 },
      { name: 'Unisex', count: 348 }
    ]
  },
  {
    id: 'offers',
    label: 'Offers',
    options: [
      { name: '0% Making Charge', count: 6 },
      { name: 'Offers', count: 6 }
    ]
  },
  {
    id: 'goldPurity',
    label: 'Gold Purity',
    options: [
      { name: '18k', count: 7664 },
      { name: '14k', count: 1188 },
      { name: '22k', count: 1399 }
    ]
  },
  {
    id: 'stones',
    label: 'Stones',
    options: [
      { name: 'Diamond', count: 5471 },
      { name: 'Diamond And Gemstone', count: 1465 },
      { name: 'Gemstone', count: 842 },
      { name: 'Pearl', count: 560 },
      { name: 'Ruby', count: 461 },
      { name: 'Sapphire', count: 385 },
      { name: 'Preset Solitaires', count: 257 },
      { name: 'Emerald', count: 243 },
      { name: 'Topaz', count: 233 },
      { name: 'Amethyst', count: 149 },
      { name: 'Citrine', count: 91 },
      { name: 'Navaratna', count: 71 },
      { name: 'Quartz', count: 52 },
      { name: 'Tanzanite', count: 46 },
      { name: 'Peridot', count: 42 },
      { name: 'Evil Eye', count: 38 },
      { name: 'Preset Solitaire Earrings', count: 36 },
      { name: 'Morganite', count: 32 },
      { name: 'Rhodolite', count: 26 },
      { name: 'Tourmaline', count: 25 },
      { name: 'Garnet', count: 21 },
      { name: 'Rose Quartz', count: 19 },
      { name: 'Aquamarine', count: 12 },
      { name: 'Crystal', count: 8 },
      { name: 'Iolite', count: 4 },
      { name: 'Tsavorite', count: 3 },
      { name: 'Carnelian', count: 1 }
    ]
  },
  {
    id: 'occasion',
    label: 'Occasion',
    options: [
      { name: 'Akshaya Tritiya', count: 8864 },
      { name: 'Weekend', count: 8561 },
      { name: 'Romance', count: 7637 },
      { name: 'Everyday Wear', count: 6156 },
      { name: 'Workwear', count: 6132 },
      { name: 'Vacation', count: 4972 },
      { name: 'Officewear', count: 3399 },
      { name: 'Festive', count: 3008 },
      { name: 'Special Occasion', count: 1201 },
      { name: 'Gifting', count: 973 },
      { name: 'Anniversary', count: 827 },
      { name: 'Gift', count: 825 },
      { name: 'Wedding', count: 627 },
      { name: 'Gift For Her', count: 562 },
      { name: 'Romantic Occasion', count: 510 },
      { name: 'Valentines Day', count: 510 },
      { name: 'Everyday', count: 508 },
      { name: 'Gifts For Her', count: 456 },
      { name: 'Family Gifting', count: 407 },
      { name: 'Spouse Gifting', count: 379 },
      { name: 'For Girlfriend', count: 376 },
      { name: 'Romantic Gifting', count: 376 },
      { name: 'Love', count: 339 },
      { name: 'Romantic', count: 339 },
      { name: 'Engagement', count: 337 },
      { name: 'For Father', count: 222 },
      { name: 'For Husband', count: 221 },
      { name: 'Gifts For Him', count: 220 },
      { name: 'For Wife', count: 169 },
      { name: 'For Sister', count: 147 },
      { name: 'Women\'s Day', count: 103 },
      { name: 'For Mother', count: 50 },
      { name: 'For Brother', count: 34 },
      { name: 'Traditional', count: 19 },
      { name: 'Festival Gifting', count: 12 },
      { name: 'Mother\'s Day', count: 12 },
      { name: 'Raksha Bandhan', count: 12 },
      { name: 'Guru Nanak Jayanti', count: 6 },
      { name: 'Ram Navami', count: 4 }
    ]
  },
  {
    id: 'numStones',
    label: '# Of Stones',
    options: [
      { name: 'Multistone', count: 6474 },
      { name: 'Single Stone', count: 859 },
      { name: 'Solitaire', count: 265 },
      { name: 'Three Stone', count: 144 },
      { name: 'Five Stone', count: 74 }
    ]
  },
  {
    id: 'style',
    label: 'Style',
    options: [
      { name: 'Light Weight Jewellery', count: 2010 },
      { name: 'Studs', count: 1420 },
      { name: 'Band', count: 708 },
      { name: 'Hoops', count: 581 },
      { name: 'Drops', count: 478 },
      { name: 'Couple Band', count: 299 },
      { name: 'Round Bangle', count: 288 },
      { name: 'Oval Bangle', count: 224 },
      { name: 'Danglers', count: 216 },
      { name: 'Multiwearable', count: 161 },
      { name: 'Y Shape', count: 130 },
      { name: 'Huggies', count: 119 },
      { name: 'Collar', count: 117 },
      { name: 'Slider', count: 113 },
      { name: 'Stackable', count: 113 },
      { name: 'Cocktail', count: 101 },
      { name: 'Sui Dhaga', count: 99 },
      { name: 'Earcuff', count: 81 },
      { name: 'Charm Bracelet', count: 74 },
      { name: 'Layered', count: 72 },
      { name: 'Jhumka', count: 71 },
      { name: 'Chevron', count: 67 },
      { name: 'Twister Bangle', count: 66 },
      { name: 'Earclimber', count: 65 },
      { name: 'Top Open', count: 63 },
      { name: 'Navaratnam Collection', count: 45 },
      { name: 'Toggle Bangle', count: 40 },
      { name: 'Vanki', count: 37 },
      { name: 'Front Back', count: 31 },
      { name: 'Hooks', count: 29 },
      { name: 'Mangalsutra Bracelets', count: 28 },
      { name: 'Halo', count: 25 },
      { name: 'Poetic Touch', count: 24 },
      { name: 'Chand Bali', count: 23 },
      { name: 'Journey', count: 23 },
      { name: 'Platinum Couple Bands', count: 21 },
      { name: 'Entangled Ode', count: 20 },
      { name: 'Trinity', count: 19 },
      { name: 'Tassel', count: 17 },
      { name: 'Imperial Nest', count: 15 },
      { name: 'Orange Peel', count: 15 },
      { name: 'Blush & Lavender Tone', count: 15 },
      { name: 'Choker', count: 13 },
      { name: 'Locket', count: 10 },
      { name: 'Cuff', count: 8 },
      { name: 'Cuff Bangle', count: 8 },
      { name: 'Multi Finger Rings', count: 8 },
      { name: 'Detachable', count: 7 },
      { name: 'Chandelier', count: 4 },
      { name: 'Roseate Smolder', count: 4 },
      { name: 'Plain Band', count: 1 }
    ]
  },
  {
    id: 'design',
    label: 'Design',
    options: [
      { name: 'Classic', count: 6495 },
      { name: 'Fashion', count: 6139 },
      { name: 'Fusion', count: 3020 },
      { name: 'Valentine Designers Pick', count: 2673 },
      { name: 'Enamel', count: 942 },
      { name: 'Modern', count: 916 },
      { name: 'Floral', count: 873 },
      { name: 'Wedding Gifts For Bride', count: 529 },
      { name: 'Hearts', count: 499 },
      { name: 'Cocktail Nights', count: 273 },
      { name: 'Religious', count: 233 },
      { name: 'Cluster', count: 207 },
      { name: 'Colorful Affair', count: 163 },
      { name: 'Eternity', count: 158 },
      { name: 'Two Tone', count: 157 },
      { name: 'Composite', count: 150 },
      { name: 'Statement', count: 141 },
      { name: 'Foliage Collection', count: 104 },
      { name: 'Station', count: 92 },
      { name: 'Alphabet', count: 91 },
      { name: 'Initial', count: 81 },
      { name: 'Butterfly', count: 71 },
      { name: 'Adams Collection', count: 48 },
      { name: 'Cross', count: 47 },
      { name: 'Tennis', count: 42 },
      { name: 'Charm', count: 40 },
      { name: 'Gold Showstoppers', count: 39 },
      { name: 'Sattva Collection', count: 29 },
      { name: 'Amiraa Collection', count: 23 },
      { name: 'Floral Mischief', count: 19 },
      { name: 'Zodiac', count: 17 },
      { name: 'Eternal Gold Collection', count: 15 },
      { name: 'Journey Collection', count: 14 },
      { name: 'Mayura Collection', count: 14 },
      { name: 'Rare Label', count: 13 },
      { name: 'Evermore Collection', count: 12 },
      { name: 'Oblici Collection', count: 12 },
      { name: 'Sacred Elements Collection', count: 11 },
      { name: 'Fashionista Collection', count: 10 },
      { name: 'Swarna Collection', count: 10 },
      { name: 'Celtic Collection', count: 9 },
      { name: 'Light On You Collection', count: 9 },
      { name: 'Long', count: 9 },
      { name: 'Saundarya Collection', count: 9 },
      { name: 'Arm Candy Collection', count: 8 },
      { name: 'Boardroom Glam 2', count: 6 },
      { name: 'Love Knot', count: 5 },
      { name: 'Promise', count: 5 },
      { name: 'Afrah Collection', count: 4 },
      { name: 'Token Of Love Collection', count: 3 },
      { name: 'Vintage', count: 3 },
      { name: 'Bouquet Of Love Collection', count: 2 },
      { name: 'Essentially Light Collection', count: 2 },
      { name: 'Fearlessly Femme', count: 2 },
      { name: 'Sound Of Love', count: 2 },
      { name: 'The Coinage Collection', count: 2 },
      { name: 'Birthstone Jewellery', count: 1 },
      { name: 'Brunch Ese', count: 1 }
    ]
  },
  {
    id: 'stoneColor',
    label: 'Stone Color',
    options: [
      { name: 'White', count: 7149 },
      { name: 'Red', count: 478 },
      { name: 'Blue', count: 332 },
      { name: 'Green', count: 290 },
      { name: 'Pink', count: 205 },
      { name: 'Yellow', count: 141 },
      { name: 'Purple', count: 133 },
      { name: 'Black', count: 59 },
      { name: 'Brown', count: 25 },
      { name: 'Off White', count: 15 }
    ]
  },
  {
    id: 'zodiac',
    label: 'Zodiac',
    options: [
      { name: 'Gemini', count: 3 },
      { name: 'Scorpio', count: 3 },
      { name: 'Libra', count: 2 },
      { name: 'Virgo', count: 2 },
      { name: 'Aquarius', count: 1 },
      { name: 'Cancer', count: 1 },
      { name: 'Capricorn', count: 1 },
      { name: 'Leo', count: 1 },
      { name: 'Pisces', count: 1 },
      { name: 'Sagittarius', count: 1 },
      { name: 'Taurus', count: 1 }
    ]
  },
  {
    id: 'stoneShape',
    label: 'Stone Shape',
    options: [
      { name: 'Round', count: 2799 },
      { name: 'Pear', count: 426 },
      { name: 'Marquise', count: 334 },
      { name: 'Princess', count: 316 },
      { name: 'Baguette', count: 272 },
      { name: 'Oval', count: 141 },
      { name: 'Cabochon', count: 140 },
      { name: 'Heart', count: 83 },
      { name: 'Button', count: 76 },
      { name: 'Emerald Cut', count: 54 },
      { name: 'Drop Plain', count: 52 },
      { name: 'Cushion', count: 50 },
      { name: 'Trillion', count: 40 },
      { name: 'Fancy', count: 34 },
      { name: 'Octagon', count: 31 },
      { name: 'Beads', count: 22 },
      { name: 'Drop Faceted', count: 10 },
      { name: 'Hexagon', count: 9 }
    ]
  },
  {
    id: 'collections',
    label: 'Collections',
    options: [
      { name: 'A La Mode Collection', count: 48 },
      { name: 'Aadya Collection', count: 4 },
      { name: 'Ain Collection', count: 6 },
      { name: 'Amour Collection', count: 7 },
      { name: 'Ani Collection', count: 13 },
      { name: 'Antra Collection', count: 15 },
      { name: 'Araya Collection', count: 11 },
      { name: 'Arles Collection', count: 13 },
      { name: 'Art Collection', count: 79 },
      { name: 'Ashta Collection', count: 8 },
      { name: 'Aurora Collection', count: 12 },
      { name: 'Ayeneh Collection', count: 12 },
      { name: 'B Iconic Collection', count: 15 },
      { name: 'Barbie', count: 38 },
      { name: 'Beatrice Collection', count: 10 },
      { name: 'Bedazzle Bracelets Collection', count: 36 },
      { name: 'Bluestone Man Collection', count: 319 },
      { name: 'Boardroom Glam Collection', count: 11 },
      { name: 'Bold Gold Collection', count: 43 },
      { name: 'Cadenza Collection', count: 1 },
      { name: 'Carnation Collection', count: 17 },
      { name: 'Cascade Collection', count: 9 },
      { name: 'Celestial Collection', count: 7 },
      { name: 'Checkmate Collection', count: 17 },
      { name: 'Chevron Rings Collection', count: 15 },
      { name: 'Clay Whispers Collection', count: 21 },
      { name: 'Colour Me Pop Collection', count: 14 },
      { name: 'Convertible Collection', count: 1 },
      { name: 'Dainty Dreams Collection', count: 74 },
      { name: 'Dear Daisy Collection', count: 8 },
      { name: 'Diva-ine Diamonds Collection', count: 60 },
      { name: 'Due Amore Collection', count: 11 },
      { name: 'Elitia Collection', count: 11 },
      { name: 'Emilie Collection', count: 5 },
      { name: 'Endless Brilliance Collection', count: 32 },
      { name: 'Ever Us Collection', count: 55 },
      { name: 'Evil Eye Collection', count: 87 },
      { name: 'Fem Delar Collection', count: 3 },
      { name: 'Fen Collection', count: 1 },
      { name: 'Flame Of The Forest Collection', count: 24 },
      { name: 'Florence Collection', count: 81 },
      { name: 'Floret Collection', count: 12 },
      { name: 'Fluo Collection', count: 37 },
      { name: 'Gemitsy Collection', count: 2 },
      { name: 'Gemphony Collection', count: 44 },
      { name: 'Glam Collection', count: 2 },
      { name: 'Greece Collection', count: 3 },
      { name: 'Hannah Collection', count: 2 },
      { name: 'Heart So Full Collection', count: 43 },
      { name: 'Hello Kitty And Friends', count: 54 },
      { name: 'Illuminati Collection', count: 10 },
      { name: 'Impression Collection', count: 6 },
      { name: 'Its A Match Collection', count: 11 },
      { name: 'Ivoire Collection', count: 12 },
      { name: 'Jodhpur Collection', count: 6 },
      { name: 'Kika Collection', count: 2 },
      { name: 'Kingdom Of Links Officewear Collection', count: 8 },
      { name: 'Kingdom Of Links Party Collection', count: 15 },
      { name: 'Knit Knot Collection', count: 1 },
      { name: 'Knots Collection', count: 10 },
      { name: 'Konark Collection', count: 3 },
      { name: 'Lattice Rebound Collection', count: 9 },
      { name: 'Liviana Collection', count: 15 },
      { name: 'Love Bands Collection', count: 19 },
      { name: 'Lumina Collection', count: 46 },
      { name: 'Mangalam Collection', count: 31 },
      { name: 'Marine Tales Collection', count: 12 },
      { name: 'Men In Bold Collection', count: 72 },
      { name: 'Meraki Collection', count: 13 },
      { name: 'Missy Collection', count: 21 },
      { name: 'Moda Beads Collection', count: 24 },
      { name: 'Morning Glory Collection', count: 2 },
      { name: 'Mystics Collection', count: 16 },
      { name: 'Neo Mint Collection', count: 5 },
      { name: 'Neovintage Collection', count: 15 },
      { name: 'Noir Blanc Collection', count: 5 },
      { name: 'Noir Collection', count: 8 },
      { name: 'Nova Collection', count: 11 },
      { name: 'Onella Collection', count: 9 },
      { name: 'Paisley Collection', count: 4 },
      { name: 'Panache Collection', count: 14 },
      { name: 'Pashmina Collection', count: 4 },
      { name: 'Pearl Blossom Collection', count: 22 },
      { name: 'Plique A Jour Collection', count: 20 },
      { name: 'Pochette Collection', count: 3 },
      { name: 'Pokémon', count: 34 },
      { name: 'Pruna Flores Collection', count: 9 },
      { name: 'Pure Love Collection', count: 71 },
      { name: 'Queen Of Gems Collection', count: 8 },
      { name: 'Rainforest Collection', count: 13 },
      { name: 'Rajwada Collection', count: 14 },
      { name: 'Rakhi Collection', count: 12 },
      { name: 'Raw Reverie Collection', count: 23 },
      { name: 'Regalia Collection', count: 15 },
      { name: 'Ren Lake Collection', count: 7 },
      { name: 'Romanisia Collection', count: 23 },
      { name: 'Roop Collection', count: 10 },
      { name: 'Sabbia Collection', count: 19 },
      { name: 'Saugat Collection', count: 4 },
      { name: 'Shalimar Collection', count: 11 },
      { name: 'Shards Collection', count: 14 },
      { name: 'Sheer Collection', count: 84 },
      { name: 'Sheer Style Collection', count: 65 },
      { name: 'Slider Rings Collection', count: 13 },
      { name: 'Soulmist Collection', count: 17 },
      { name: 'Spectrum Collection', count: 4 },
      { name: 'Starlight Collection', count: 5 },
      { name: 'Sway Collection', count: 7 },
      { name: 'Tarsie Collection', count: 3 },
      { name: 'Teori Collection', count: 12 },
      { name: 'The Greece Collection', count: 23 },
      { name: 'The Rainforest Collection', count: 16 },
      { name: 'The Uphaaar Collection', count: 78 },
      { name: 'The Y Necklaces Collection', count: 16 },
      { name: 'Thumb Rings Collection', count: 12 },
      { name: 'Toi Et Moi Collection', count: 20 },
      { name: 'Tropica Collection', count: 5 },
      { name: 'Tucked Collection', count: 9 },
      { name: 'Uphaar Collection', count: 10 },
      { name: 'Vanya Collection', count: 5 },
      { name: 'Venezia Collection', count: 11 },
      { name: 'Viva Pride Collection', count: 30 },
      { name: 'Wired Collection', count: 44 },
      { name: 'You And Me Collection', count: 35 },
      { name: 'Elysian Collection', count: 10 },
      { name: 'Grazia Collection', count: 13 },
      { name: 'Precious Promise Collection', count: 22 },
      { name: 'Pride Collection', count: 21 },
      { name: 'Runway Collection', count: 24 },
      { name: 'Silene Collection', count: 16 }
    ]
  },
  {
    id: 'tanmaniya',
    label: 'Tanmaniya',
    options: [
      { name: 'Mangalsutra Pendant', count: 154 }
    ]
  },
  {
    id: 'characteristics',
    label: 'Characteristics',
    options: [
      { name: 'Textured', count: 20 },
      { name: 'Panda', count: 6 },
      { name: 'Tulip', count: 1 }
    ]
  }
];
